### ISSUE TITLE
Marauders support

### ISSUE THREAD

**Issue by bsormagec** [Dylan-Zheng/Rise-of-Kingdoms-Bot#107]
Anyone can add marauder's support? @kunalkapoor

**Comment by kunalkapoor** [comment]
@bsormagec This is a much more difficult thing to add. Marauders aren't searchable using a button - they have to be looked for by scrolling the map, Also, they keep moving around, so it's hard to pinpoint exactly where they'll be. It's not impossible - it will just be a inaccurate.

Unfortunately I have stopped playing RoK so I'm not really contributing to this repo anymore. Hopefully someone else takes this up.

**Comment by bsormagec** [comment]
Thank you so much
