### ISSUE TITLE
Can you update executable version

### ISSUE THREAD

**Issue by Phoenix10King** [Dylan-Zheng/Rise-of-Kingdoms-Bot#12]
As the title..
Can you update executable version with the new updates?

**Comment by Dylan-Zheng** [comment]
Sure, check here: https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.2.1.031421_beta

**Comment by Phoenix10King** [comment]
Perfect thanks

**Comment by Phoenix10King** [comment]
Buddy can you update again? 😁
