### ISSUE TITLE
Window is too large/big

### ISSUE THREAD

**Issue by Phoenix10King** [Dylan-Zheng/Rise-of-Kingdoms-Bot#13]
New problem bro
The window is too large/big so resource part and start/stop part can't be reach...

![IMG_20210314_234902](https://user-images.githubusercontent.com/20769862/111085509-5c5d5400-8520-11eb-9195-9f4533638f0d.jpg)

![IMG_20210314_234911](https://user-images.githubusercontent.com/20769862/111085522-67b07f80-8520-11eb-83e7-b407f2e765a7.jpg)

**Comment by Dylan-Zheng** [comment]
ops..., when i fix it, I will let you know in here :joy:

**Comment by Dylan-Zheng** [comment]
Fixed in new release 
https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.2.2.031421_beta

**Comment by Phoenix10King** [comment]
You are the best... Thank you 😎😂
