### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by maxdu75** [Dylan-Zheng/Rise-of-Kingdoms-Bot#131]
![image](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/assets/142407825/59850385-88a7-4908-853b-9f68a4b04d73)
How do I get this information?

**Comment by silverwolfceh** [comment]
You need to install Memu player, then you fill the ip is: 127.0.0.1 and port is: 21503. Name can be anything
