### ISSUE TITLE
Attacking barbarians 

### ISSUE THREAD

**Issue by Phoenix10King** [Dylan-Zheng/Rise-of-Kingdoms-Bot#15]
Bro attacking barbarians not working..
Also please check again the reset at 00:05 utc

![IMG_20210317_180107](https://user-images.githubusercontent.com/20769862/111498872-0a4c4680-874b-11eb-8360-115b17258be8.jpg)

**Comment by Dylan-Zheng** [comment]
it is always not working, or just sometime

**Comment by Phoenix10King** [comment]
Always 😊
I tried to set attack to all colours but still nothing

**Comment by Dylan-Zheng** [comment]
I don't what cause it on you PC, but if possible could you share gif/video when bot begin the task, that will help a lot.
I have been test and run on  my accounts for 5 days, and has no problem.
![](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/blob/main/docs/atk_bb.gif?raw=true)

**Comment by Phoenix10King** [comment]
what screen recorder do you use ???

**Comment by Dylan-Zheng** [comment]
> what screen recorder do you use ???
ScreenToGif

**Comment by qbbyybyby** [comment]
> I don't what cause it on you PC, but if possible could you share gif/video when bot begin the task, that will help a lot.
> I have been test and run on my accounts for 5 days, and has no problem.
> ![](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/blob/main/docs/atk_bb.gif?raw=true)

Mine work to New Troops step but it not use March

**Comment by qbbyybyby** [comment]
Traceback (most recent call last):
  File "bot_related\device_gui_detector.py", line 177, in barbarians_level_image_to_string
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "tasks\Barbarians.py", line 87, in do
  File "tasks\Barbarians.py", line 256, in select_save_blue_one
RuntimeError: Save not found
