### ISSUE TITLE
运行打印出来的日志

### ISSUE THREAD

**Issue by hkforever** [Dylan-Zheng/Rise-of-Kingdoms-Bot#16]
D:\PycharmProjects\pythonProject\venv\Scripts\python.exe D:/PycharmProjects/pythonProject/RoKBot/Rise-of-Kingdoms-Bot/main.py
Traceback (most recent call last):
  File "D:\PycharmProjects\pythonProject\RoKBot\Rise-of-Kingdoms-Bot\gui\creator.py", line 157, in load_building_pos
    with open(resource_path(FilePaths.SAVE_FOLDER_PATH.value + "{}_building_pos.json".format(prefix)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\PycharmProjects\\pythonProject\\RoKBot\\Rise-of-Kingdoms-Bot\\save\\127.0.0.1_5555_building_pos.json'

**Comment by Dylan-Zheng** [comment]
当建筑坐标获取完后，会创建一个{ip}_building_pos.json。所以第二次打开就不会有这个报错了。
建筑获取的时间会比较长。
