### ISSUE TITLE
IP and PORT

### ISSUE THREAD

**Issue by kostasdes** [Dylan-Zheng/Rise-of-Kingdoms-Bot#18]
Hey i ahve a question aboutthe ip and the port in the executable programm, i seem to understand i need to give the ip of the device, but i cant find the ip it requires(I play in bluestacks) and the port in question. Can anyone give a hand?

**Comment by kostasdes** [comment]
I use the ip and port under the adb in the preferences but it doenst seem to be working.. it sill says disconected

**Comment by Dylan-Zheng** [comment]
close bot. open windows power shell, got adb folder, type following command:
``` 
.\adb.exe kill-server
```
restart bot.  see if it working

**Comment by kostasdes** [comment]
Still seem to have a problem.. i have killed and started the adb server a few times, doesnt seem to work for me. Do you have a reference video on what to use on ip and port brackets? That would help me a lot :) The bot though even i didnt started it seems to have nice code! Good work guys

**Comment by Dylan-Zheng** [comment]
Could you post your console output. 
By the way, are you using executable version from here: [https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/)
or you just clone code run by yourself?

**Comment by kostasdes** [comment]
So fast forward, i managed to connect the programm, but does the building progress take that long? in the console it says building_pos.json doesnt exist.

**Comment by Dylan-Zheng** [comment]
Unfortunately, yes, building progress take a long time about 20 ~ 30 mins, I guess. but it will only do once.

building_pos.json will be create after locating building position

**Comment by Dylan-Zheng** [comment]
New version allow to manually configure building position

Link: [https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.3.2.033121_beta](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.3.2.033121_beta)
