### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Melburne212** [Dylan-Zheng/Rise-of-Kingdoms-Bot#19]
![image](https://user-images.githubusercontent.com/45775203/112092328-51ea2c80-8ba8-11eb-9463-e1213a4bf1c6.png)

**Comment by Dylan-Zheng** [comment]
Could you post your 

.\save\[ip]_building_pos.json 

It's happening because orc doesn't read image correctly.

**Comment by Melburne212** [comment]
[](url)
