### ISSUE TITLE
Emulator Support

### ISSUE THREAD

**Issue by leonyonz** [Dylan-Zheng/Rise-of-Kingdoms-Bot#2]
Hello, is this support with NOX ?

**Comment by Dylan-Zheng** [comment]
I haven't test on NOX, but it should support any emulator, just set screen resolution to 720 x 1280 or 1280 x 720, and enable ADB

**Comment by Dylan-Zheng** [comment]
> Hello, is this support with NOX ?

I haven't test on NOX, but it should support any emulator, just set screen resolution to 720 x 1280 or 1280 x 720, and enable ADB

**Comment by leonyonz** [comment]
Thank you, is there a wiki to run it ? 
when im execute main.py it show adb version 41 required, but i didnt find adb 41 for windows

**Comment by Dylan-Zheng** [comment]
> Thank you, is there a wiki to run it ?
> when im execute main.py it show adb version 41 required, but i didnt find adb 41 for windows

adb 41 is adb version 29.0.5-5949299 (1.0.41)
There is not wiki, but I just update readme file. it should have enough information to start the script.
