### ISSUE TITLE
adb devices show as disconnected

### ISSUE THREAD

**Issue by 1851ROK** [Dylan-Zheng/Rise-of-Kingdoms-Bot#20]
Hi,

I can connect to the adb device via CMD but the program console shows them as disconnected and therefore it is not working.
![adbDisconnected](https://user-images.githubusercontent.com/81327104/112369843-59632000-8ce5-11eb-8a22-b9f56a06ead9.png)

**Comment by Dylan-Zheng** [comment]
I need output from bot's console.
if you are using executable version, there should have a console start with it.

**Comment by Dylan-Zheng** [comment]
> Hi,
> 
> I can connect to the adb device via CMD but the program console shows them as disconnected and therefore it is not working.
> ![adbDisconnected](https://user-images.githubusercontent.com/81327104/112369843-59632000-8ce5-11eb-8a22-b9f56a06ead9.png)

Also from the image: show that you devices is not connect to adb.
emulator-5554 is not you device.

you device should be 10.0.2.15:5555

**Comment by 1851ROK** [comment]
Thanks the 127.0.0.1:5555 worked!
