### ISSUE TITLE
Not recognizing building

### ISSUE THREAD

**Issue by 1851ROK** [Dylan-Zheng/Rise-of-Kingdoms-Bot#22]
Hi,

How can I troubleshoot that?
When I start it for the first time, I see the progress % going up, in addition to that I can see it clicks on a building (without clicking the info button) and it doesn't write down that a building was found.
When the progress ends, it just click on the build option and gems buying.
In the CMD I see at the end issue with barracks, going to the building file I can see it is empty.

Thanks!

**Comment by Dylan-Zheng** [comment]
> Hi,
> 
> How can I troubleshoot that?
> When I start it for the first time, I see the progress % going up, in addition to that I can see it clicks on a building (without clicking the info button) and it doesn't write down that a building was found.
> When the progress ends, it just click on the build option and gems buying.
> In the CMD I see at the end issue with barracks, going to the building file I can see it is empty.
> 
> Thanks!

I notice that, especially when city hall level is lower then 16. 

below is temporary solution:
1. create a **json** file under bot/save/ip_port_building_pos.json (ex: 127.0.0.1_5555_building_pos.json)
2. copy & paste following 
```json
{
    "alliance_center": [
        628,
        251
    ],
    "tavern": [
        691,
        251
    ],
    "goldmine": [
        376,
        407
    ],
    "quarry": [
        439,
        459
    ],
    "barracks": [
        754,
        355
    ],
    "stable": [
        817,
        303
    ],
    "blacksmith": [
        943,
        303
    ],
    "archery_range": [
        880,
        355
    ],
    "lumber_mill": [
        439,
        511
    ],
    "farm": [
        502,
        563
    ],
    "siege_workshop": [
        754,
        459
    ],
    "hospital": [
        628,
        563
    ]
}
```
3. replace x and y position to your building position
4. open ip_port_config.json (ex: 127.0.0.1_5555_config.json), find and set hasBuildingPos to **true**

Another solution(may also fix it):
[https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/issues/9#issuecomment-791843808](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/issues/9#issuecomment-791843808)

**Comment by 1851ROK** [comment]
Thanks! Ya this is a test new account CH level 5 :)
Might be a stupid question, sorry, but how do I know the actual location? I mean I also saw the other comment but can't understand associate the red square to a numbers location.

**Comment by Dylan-Zheng** [comment]
You can use paint.net / photoshop to get your building position:
1. open paint.net and set view as follow:
![Screenshot 2021-03-29 151614](https://user-images.githubusercontent.com/71362955/112888032-de618700-90a1-11eb-9fdc-6433324f39ac.png)
2. move you mouse to the building, then zoom in: 
![Screenshot 2021-03-29 152006](https://user-images.githubusercontent.com/71362955/112888537-752e4380-90a2-11eb-8a22-fb910bc622fa.png)
3. x in top ruler, y in left ruler

ex: 
```json
{
    "goldmine": [
        513,
        295
    ],
}
```

**Comment by Dylan-Zheng** [comment]
New version allow to manually configure building position

Link: [https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.3.2.033121_beta](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.3.2.033121_beta)

**Comment by 1851ROK** [comment]
You are amazing!!
