### ISSUE TITLE
Issues in new version

### ISSUE THREAD

**Issue by 1851ROK** [Dylan-Zheng/Rise-of-Kingdoms-Bot#24]
Hi,

I think there are few issues in new version, wanted to get your opinion and assistance.

1. If you click on "Building Pos" before pressing start, you get an error when trying to position buildings:
"TypeError: 'NoneType' objects does not support item assignment"
From looking at the code it seems like the start function that solves the issue by overwriting the initial none assignment is done only after start.
However I would assume we need to position the building before starting.

2. Even after I start and then do building position, the file building position doesn't exist so it won't alow me to save the coordinates, had to manually create it.

3. Even that now my cordinates are correct in the building_pos file, when I press start I get "KeyError: 'hospital' and therefore it never actually starts.

4. When I try to click stop I get "Eception in TKinter callback" and "ValueError: invalid thread id" so it remains on start.

**Comment by Dylan-Zheng** [comment]
fixed [Click Me](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.4.1.040221_beta)
