### ISSUE TITLE
code refactorisation?

### ISSUE THREAD

**Issue by seashell-freya** [Dylan-Zheng/Rise-of-Kingdoms-Bot#25]
Hi, do you have any plan to refactor your codes so they are easier to work with? It would be helpful to split functions in bot.py into multiple files, e.g. helper_tasks.py, simple_tasks.py, barb.py, gather.py etc. 😊

**Comment by Dylan-Zheng** [comment]
Yea, that is what I'm doing recently. debug and rewrite code. try to make it readable. lol
