### ISSUE TITLE
ingame captcha

### ISSUE THREAD

**Issue by PFocus133** [Dylan-Zheng/Rise-of-Kingdoms-Bot#26]
Can you tell us more about solving captcha in the game? whatever I try, it doesn't work for me. And thank you, this is really cool soft

**Comment by 1851ROK** [comment]
@PFocus133, In other issues here, he mentioned that you need account in 2captcha, have you done that?

**Comment by Dylan-Zheng** [comment]
> Can you tell us more about solving captcha in the game? whatever I try, it doesn't work for me. And thank you, this is really cool soft

I was using two 2captcha to solving captcha in the game. 
2captcha is a third party server who take the captcha and will return answer. and it needs pay. but very cheap.

site: [https://2captcha.com/](https://2captcha.com/)

**Comment by PFocus133** [comment]
> > Can you tell us more about solving captcha in the game? whatever I try, it doesn't work for me. And thank you, this is really cool soft
> 
> I was using two 2captcha to solving captcha in the game.
> 2captcha is a third party server who take the captcha and will return answer. and it needs pay. but very cheap.
> 
> site: https://2captcha.com/

i know. but it still dont work for me

**Comment by PFocus133** [comment]
I solved the problem in the weirdest way. It was about the resolution of the bluestaсks screen. I changed from 1280x720 to 720x1280 and somewhy it worked. Thanks for your hard work.
