### ISSUE TITLE
~Feature Request~ | Close game for set amount of time

### ISSUE THREAD

**Issue by 1851ROK** [Dylan-Zheng/Rise-of-Kingdoms-Bot#28]
Hi,

As you know, there are no players who actually play 24/7, to avoid the possibility of getting banned, I would like to know if it is possible or requests a feature that actually closes the game for a specific amount of time, i.e 1h, 8h etc.

It will mimic the overnight sleep and the 30m - 2h that we are off between login times.

Regards,
:)

**Comment by PFocus133** [comment]
good idea

**Comment by Dylan-Zheng** [comment]
sure. i will add it on next version

**Comment by Dylan-Zheng** [comment]
add and updated
