### ISSUE TITLE
Issue | Captcha failing - ERROR_TOO_BIG_CAPTCHA_FILESIZE

### ISSUE THREAD

**Issue by 1851ROK** [Dylan-Zheng/Rise-of-Kingdoms-Bot#31]
Hi,

I am getting sometimes an error w/ captcha RuntimeError: 2Captcha Error: ERROR_TOO_BIG_CAPTCHA_FILESIZE.

Thanks!

**Comment by Dylan-Zheng** [comment]
I fixed it. will be update next version. it should either this week or next week.

**Comment by Dylan-Zheng** [comment]
fixed and upaded
