### ISSUE TITLE
Position set 

### ISSUE THREAD

**Issue by BTMRer** [Dylan-Zheng/Rise-of-Kingdoms-Bot#35]
Every time that i try to set the position of buildings the program open the gem store and set that as the city image, also when try to execute any task open it again the gem shop cant use it bz of that. Maybe im doing something wrong?.
![111](https://user-images.githubusercontent.com/84462644/118848389-b66df300-b89c-11eb-8c44-c8940d2ccd49.PNG)

**Comment by 1851ROK** [comment]
Are you using the latest version? I think Dylan switch the view to city editor view so it won't enter the VIP area.

**Comment by BTMRer** [comment]
Yes is the last version it try to enter to city editor but end entering to gem shop.

**Comment by BTMRer** [comment]
i think is bz my ch is lv 10? read that in some of the issue.

**Comment by BTMRer** [comment]
Just figured out that you need to have lv 7 CH if you want to use the program, because at that lv you open the city editor and the program need that to position it.
