### ISSUE TITLE
Community | Any tips of not getting bans?

### ISSUE THREAD

**Issue by 1851ROK** [Dylan-Zheng/Rise-of-Kingdoms-Bot#36]
![image](https://user-images.githubusercontent.com/81327104/119313220-fad20800-bc7b-11eb-9113-21f0fdc051c8.png)
Just got banned on the dedicated farm account, any tips to avoid that :) ?

**Comment by BTMRer** [comment]
do you have the 2chaptcha solver active?

**Comment by Dylan-Zheng** [comment]
Is anyone report you? I don't know how they found out you are using bot.
If they are detect you by repeat action, what I can do is add random action on every task, and disorder tasks.

**Comment by 1851ROK** [comment]
I don't think someone reported on me, and the captcha solver was on.
Are you using it 24/7? as it was running for 24/7.

I will now use the feature from #28 to see if it will help

**Comment by Dylan-Zheng** [comment]
I do run it 24/7. may be I just get lucky.

**Comment by Dylan-Zheng** [comment]
fix terminate game while break

**Comment by yuceltoluyag** [comment]
This problem is not related to the bot, because I forgot to verify for 10 minutes, the system is automatically banned for 24 hours.

![image](https://user-images.githubusercontent.com/16064131/122216479-1e702300-ceb5-11eb-9322-3bc9b92d5141.png)
