### ISSUE TITLE
Quit the game to take a break 

### ISSUE THREAD

**Issue by BTMRer** [Dylan-Zheng/Rise-of-Kingdoms-Bot#39]
![111](https://user-images.githubusercontent.com/84462644/119772280-e9137f00-be8c-11eb-9075-d17b6517f110.PNG)

Hi was trying the new function and when the bot take the break of the game and try to enter again the game always close before enter again. 

...btw i think a really nice feature will be lyceum exam taker the normal exam and the final one.

here is the git of one that have that but was trying and fail sometimes and always open the explorer bz dont know what to select i think that script is a good start. 

https://github.com/GabrielAgrela/ROKBOT/blob/master/README.md

hope that help if you decide to implement it. THANKS FOR THIS GREAT PY BOT

**Comment by Dylan-Zheng** [comment]
I fixed it by put auto restart game with take break together. new version will be upload with in two days.
about lyceum exam, I'm working on it. but will not be done recently.
