### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'serial'

### ISSUE THREAD

**Issue by leonyonz** [Dylan-Zheng/Rise-of-Kingdoms-Bot#4]
Hello, i have problem when running the program, here the log

```
C:\Users\leonardus\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/leonardus/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:\Users\leonardus\PycharmProjects\pythonProject\main.py", line 11, in <module>
    main()
  File "C:\Users\leonardus\PycharmProjects\pythonProject\main.py", line 6, in main
    window = MainWindow(adb)
  File "C:\Users\leonardus\PycharmProjects\pythonProject\gui\main_window.py", line 43, in __init__
    mf = MainFrame(self.window, self.adb.get_device(), width=size[0], height=size[1])
  File "C:\Users\leonardus\PycharmProjects\pythonProject\gui\main_frame.py", line 24, in __init__
    self.bot_config = load_bot_config(device.serial.replace(':', "_"))
AttributeError: 'NoneType' object has no attribute 'serial
```

Im already installed pyserial but still not work

**Comment by Dylan-Zheng** [comment]
That will be cause by following conditions:

**Comment by Dylan-Zheng** [comment]
> Hello, i have problem when running the program, here the log
> 
> ```
> C:\Users\leonardus\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/leonardus/PycharmProjects/pythonProject/main.py
> Traceback (most recent call last):
>   File "C:\Users\leonardus\PycharmProjects\pythonProject\main.py", line 11, in <module>
>     main()
>   File "C:\Users\leonardus\PycharmProjects\pythonProject\main.py", line 6, in main
>     window = MainWindow(adb)
>   File "C:\Users\leonardus\PycharmProjects\pythonProject\gui\main_window.py", line 43, in __init__
>     mf = MainFrame(self.window, self.adb.get_device(), width=size[0], height=size[1])
>   File "C:\Users\leonardus\PycharmProjects\pythonProject\gui\main_frame.py", line 24, in __init__
>     self.bot_config = load_bot_config(device.serial.replace(':', "_"))
> AttributeError: 'NoneType' object has no attribute 'serial
> ```
> 
> Im already installed pyserial but still not work

That will be cause by following conditions:

1. target device is offline
2. device adb is not turn on 
3. device ip and port is not on ip - 127.0.0.1 and port 5555

if you are in third condition, you can edit following code in main_windows.py
`mf = MainFrame(self.window, self.adb.get_device(device_ip, device_port), width=size[0], height=size[1])`

**Comment by leonyonz** [comment]
great, 
![image](https://user-images.githubusercontent.com/42370275/109750982-12b36600-7c10-11eb-90e4-47693760fd07.png)
