### ISSUE TITLE
not able to verifiy 

### ISSUE THREAD

**Issue by BasedJumper** [Dylan-Zheng/Rise-of-Kingdoms-Bot#41]
It has a problem recognizing it needs to do a verification. You have to manually open the verification chest and click verify for it to do the task.

**Comment by Dylan-Zheng** [comment]
when count down reach 1 mins, chest will automatically open.

**Comment by BasedJumper** [comment]
Right, but the chest will not open and it zeroes out. I'll get a screenshot next time.

**Comment by Dylan-Zheng** [comment]
That is odd, because Rok itself will open that chest and popup verify windows before it zeroes out.
screenshot is good, but if you could also provide me output from the terminal that will be great, thx.

**Comment by leety** [comment]
On a side note of this issue.  I am using 2 captcha with a user key (positive balance). but is unable to pass the verification.  Is the haoi method better suited?

The window size is 470X850, I did not change it.

**Comment by Ministrz** [comment]
> Right, but the chest will not open and it zeroes out. I'll get a screenshot next time.

Does it work? Did you solve the problem?
