### ISSUE TITLE
Question about init view process

### ISSUE THREAD

**Issue by leonyonz** [Dylan-Zheng/Rise-of-Kingdoms-Bot#5]
Hi im again, 
Can you describe what init view do ?

![image](https://user-images.githubusercontent.com/42370275/109754161-1fd35380-7c16-11eb-9b26-e8780d84d469.png)

Is every the first run need to do init view ?

Thank you

**Comment by leonyonz** [comment]
Update, the init process always loop to 0% :

![image](https://user-images.githubusercontent.com/42370275/109758239-da1a8900-7c1d-11eb-810f-cca9d8cc8a97.png)

**Comment by Dylan-Zheng** [comment]
”init view“ has noting to do with that progress. it just make sure your device have full view of your city.

your current task is "initialize building position", this is happened your when you first connect bot with you device.
this progress will take about 20 mins - 40mins. but it will only do once.
during this progress, bot will locating your building position. 
after progress reach to 100%, bot will save your building position to ./save/127.0.0.1_5555_building_pos.json.
if you stop in the middle, bot will restart from 0% next time


I see what your doing is try to have same building position as I show in the gif, but that is not required. 
you can place you building in any location as long as they are in box( left: 250, right: 950, top: 95, bottom: 615)

**Note: Do NOT touch any thing in the game during this progress.** 

contents of 127.0.0.1_5555_building_pos.json.
`
{
    "storehouse": [
        628,
        147
    ],
    "lyceum_of_wisdom": [
        691,
        199
    ],
    "scout_camp": [
        502,
        251
    ],
    "trading_post": [
        565,
        199
    ],
    "alliance_center": [
        628,
        251
    ],
    "city_hall": [
        880,
        251
    ],
    "academy": [
        565,
        251
    ],
    "tavern": [
        691,
        251
    ],
    "monument": [
        754,
        251
    ],
    "builder's_hut": [
        376,
        355
    ],
    "courier_station": [
        439,
        303
    ],
    "goldmine": [
        376,
        407
    ],
    "quarry": [
        439,
        459
    ],
    "shop": [
        628,
        303
    ],
    "barracks": [
        754,
        355
    ],
    "stable": [
        817,
        303
    ],
    "blacksmith": [
        943,
        303
    ],
    "castle": [
        313,
        355
    ],
    "archery_range": [
        880,
        355
    ],
    "lumber_mill": [
        439,
        511
    ],
    "farm": [
        502,
        563
    ],
    "siege_workshop": [
        754,
        459
    ],
    "hospital": [
        628,
        563
    ]
}
`

**Comment by leonyonz** [comment]
okay, i will try again and update to this ticket

**Comment by leonyonz** [comment]
Updated, i have try to not doing anything when process but the progress still reset to 0%
Is there a log or debug ?

**Comment by Dylan-Zheng** [comment]
could you tell me what files are under ./save

**Comment by leonyonz** [comment]
Here you go :

![image](https://user-images.githubusercontent.com/42370275/109856674-577ce280-7c8c-11eb-8461-556f7899b6e3.png)

**Comment by Dylan-Zheng** [comment]
it look likes it didn't save you building position. into file **.\save\127.0.0.1_62001_building_pos.json**
I need to double check my code. I will let you  know, when I found out.

**Comment by Dylan-Zheng** [comment]
btw, what os are you using. it doesn't look likes windows

**Comment by leonyonz** [comment]
Its Windows 10, 
Im using cygwin for run command line since i not familliar with CMD

btw, first time i running the program it show error : `[Errno 2] No such file or directory:` 

![image](https://user-images.githubusercontent.com/42370275/109858212-1e457200-7c8e-11eb-989e-3c71a39671f0.png)

So i make the save dir manually,

**Comment by leonyonz** [comment]
I think im figure it out what happens, im forgot to move tesseract 😂
I will try it again

**Comment by leonyonz** [comment]
WOW its working now

**Comment by Dylan-Zheng** [comment]
> WOW its working now

Still working? I don't know what commit version you are using.
but I found out the bug, that is because I store building position in the config file. that main reason cause that bug.
also there  few other bug relate to that.

**Comment by leonyonz** [comment]
Updated :
The program running well after the init progress but the config not saved, so when i stop the bot it will be init building again from beginning.

**Comment by Dylan-Zheng** [comment]
Update:
I just update repository, bugs that your mention are all fixed.

**Comment by leonyonz** [comment]
I see you add input for adb host, im very excited to try the bot for multi device 😄 
anyway, im testing for some feature and i think it's works now thank you very much.

I will submit a new ticket if i found new issue there.

**Comment by leonyonz** [comment]
Oh, one last questions
Is the captcha verification need buy some user key first to use ?

**Comment by Dylan-Zheng** [comment]
> Oh, one last questions
> Is the captcha verification need buy some user key first to use ?

yes, both 'haoi' and 'captcha verification' are 3th party cloud server, use to pass the verification, and need to pay.

currently, I don't have any idea how to pass verification locally.

**Comment by leonyonz** [comment]
Thank you very much, i think case solved.

**Comment by Phoenix10King** [comment]
> > Oh, one last questions
> > Is the captcha verification need buy some user key first to use ?
> 
> yes, both 'haoi' and '2captcha' are 3th party cloud server, use to pass the verification, and need to pay.
> 
> currently, I don't have any idea how to pass verification locally.
> 
> btw, i also upload an executable version of bot [Ckick me](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.1.1.030321_beta)

Basically bot cannot bypass captcha automatically?? We need to make this manually??

**Comment by Dylan-Zheng** [comment]
@Phoenix10King 

It does bypass captcha automatically if you have **2captcha** account. otherwise it doesn't.

**Comment by Phoenix10King** [comment]
> @Phoenix10King
> 
> It does bypass captcha automatically if you have **2captcha** account. otherwise it doesn't.

Were can i found a 2 captcha account? And what is te cost?

**Comment by Phoenix10King** [comment]
Is that website?? 

https://2captcha.com/2captcha-api

Which one i have to choose?
