### ISSUE TITLE
Break time custom

### ISSUE THREAD

**Issue by leonyonz** [Dylan-Zheng/Rise-of-Kingdoms-Bot#6]
Hello, 

If i want to custom the break time, Is it just changing the Value option of `x` Minute ?

![image](https://user-images.githubusercontent.com/42370275/109995753-28747880-7d41-11eb-9df6-35621abc950f.png)

```
def time_drop_down(app, parent):
    value = '{} Minute'.format(int(app.bot_config.breakTime / 60))
    options = ['1 Minute', '2 Minute', '3 Minute', '4 Minute', '5 Minute', '10 Minute', '15 Minute', '20 Minute']
    variable = StringVar()
    variable.set(value)

    def command(value):
        app.bot_config.breakTime = int(value.replace(' Minute', '')) * 60

    option = OptionMenu(parent, variable, *options, command=command)
    return option, variable
```

**Comment by Dylan-Zheng** [comment]
That right, but change "time_drop_down" function in all_title_fns.py

and add one line like this. this bug just found out form the image.
`
app.bot_config.breakTime = int(value.replace(' Minute', '')) * 60
write_bot_config(app.bot_config, app.device.serial.replace(':', "_")) #use to save config to file
`
