### ISSUE TITLE
Ready to GO ??? 

### ISSUE THREAD

**Issue by Phoenix10King** [Dylan-Zheng/Rise-of-Kingdoms-Bot#7]
Good morning sir

this version of your bot is the same with the version here ???  [(bot)](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot)

also this version its ready to go ?? i mean plug and play ?
or you need to set something in order to manage it to work properly ???

**Comment by Dylan-Zheng** [comment]
this is last version：https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.1.1.030321_beta
and yes, download for use
