### ISSUE TITLE
How to get bluestacks Ip and port ???

### ISSUE THREAD

**Issue by Phoenix10King** [Dylan-Zheng/Rise-of-Kingdoms-Bot#8]
bot asking for emulator ip and port !!! how can i get this ???

**Comment by Phoenix10King** [comment]
i think i found it out .. its under Emulator Android Debug Bridge (ADB) ...

second question
what keys i need to use for captcha ??

**Comment by Dylan-Zheng** [comment]
[check here](https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/issues/5#issuecomment-790291654)
