### ISSUE TITLE
Bot Can't locate correctly the buildings 

### ISSUE THREAD

**Issue by Phoenix10King** [Dylan-Zheng/Rise-of-Kingdoms-Bot#9]
Hello again sir
I have hard time trying to manage your bot to work.. 
Until now i tried 3 times to locate the buildings but bot cant do it correctly.. 

I use msi blustacks emulator 
And 1280x720 resolution 

It starts normally to locate the buildings, by centering the screen but after some time it move the screen lower.. 

This has as problem not to locate the buildings below.. 

![IMG_20210306_022042](https://user-images.githubusercontent.com/20769862/110188300-d9534400-7e23-11eb-88aa-a74aa014b5d5.jpg)

Any idea how to fix this??

**Comment by Dylan-Zheng** [comment]
Reason why it will move down because when bot tap on building in the bottom. Game will try to move the screen to display the button. To fix it try to put all your buildings in the center

**Comment by Phoenix10King** [comment]
Ok i will try to manage like this and let you know..

**Comment by Phoenix10King** [comment]
Everything is fine
Bot works perfectly... 

Just a request... 

Is it possible to add peerleess scholar answers as option and building upgrades??
